// Code generated by github.com/stealthmodesoft/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/stealthmodesoft/gqlgen/_examples/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
