#!/bin/bash

set -euo pipefail

gqlgen_dir=$(pwd)
cd $(mktemp -d)
go mod init inittest
go mod edit -replace=github.com/stealthmodesoft/gqlgen="$gqlgen_dir"
go get -d github.com/stealthmodesoft/gqlgen

if ! go run github.com/stealthmodesoft/gqlgen init &>/dev/null ; then
    echo "gqlgen init failed"
    exit 125
fi
